include version.mk
CC = gcc
AR = ar
PROJECT_NAME = sf
CLIENT = $(PROJECT_NAME)-client
CLIENT_STATIC = $(CLIENT)-static
SERVER = $(PROJECT_NAME)-server
SERVER_STATIC = $(SERVER)-static
LIBNAME = $(PROJECT_NAME)
SONAME = lib$(LIBNAME).so.$(VERSION_MAJOR)
SHARED_LIB = $(SONAME).$(VERSION_MINOR)
STATIC_LIB = lib$(LIBNAME).a
OPTIMIZE= -g -O0
CPPFLAGS= -DVERSION_MAJOR=$(VERSION_MAJOR) -DVERSION_MINOR=$(VERSION_MINOR)
CFLAGS = -fPIC $(CPPFLAGS) $(OPTIMIZE) -Wall
ARFLAGS = rvs
